services:
  - type: web
    name: documind-ai
    env: python
    region: oregon
    plan: starter
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python documind_main.py
    healthCheckPath: /health
    envVars:
      - key: VECTOR_DB_PROVIDER
        value: pinecone
      - key: RERANKER_PROVIDER
        value: cohere
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.11.0
